config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  
  get '/contact', to: 'messages#new', as: 'contact'
  post '/contact', to: 'messages#create'

  get '/about', to: 'pages#about'

  devise_for :users

  resources :posts do
    resources :comments
  end

  root to: "posts#index"
  match 'posts/:id/publish' => 'posts#publish', :via => :get, :as => :publish_post
  match 'posts/:id/unpublish' => 'posts#unpublish', :via => :get, :as => :unpublish_post

  get 'tags/:tag', to: 'posts#index', as: "tag"
  get 'tags/', to: 'tags#index', as: "tags"
  get 'taggings/', to: 'taggings#index', as: "taggings"
  match 'taggings/:id' => 'taggings#destroy', :via => :delete, :as => :delete_tagging
  match 'tags/:id' => 'tags#destroy', :via => :delete, :as => :delete_tag

  match '/users',   to: 'users#index',   via: 'get'
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'users/:id' => 'users#show', :via => :get, :as => :admin_show_user
  match 'users/:id' => 'users#update', :via => :get, :as => :admin_edit_user

  match '/comments',   to: 'comments#index',   via: 'get', :as => :all_comments
  match '/comments/:id',   to: 'comments#show',   via: 'get', :as => :show_comment

  devise_scope :user do
    get "/admin" => "devise/sessions#new"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	validates :commenter, presence: true, length: {minimum: 1}
	validates :body, presence: true, length: {minimum: 5}
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "your_email@example.org",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/message.rb
class Message

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :content,
    presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :nullify
  has_many :tags, dependent: :nullify, through: :taggings

	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true

	extend FriendlyId
	friendly_id :title, use: :slugged

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
  end

  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end

 def next
 	 Post.where("id > ?", id).limit(1).first
	end

	def prev
  	Post.where("id < ?", id).limit(1).first
	end

	has_many :post_attachments
 	accepts_nested_attributes_for :post_attachments
end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
	mount_uploader :post_image, PostImageUploader
   	belongs_to :post
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings, dependent: :destroy
	has_many :posts, dependent: :nullify, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end

	def manage
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

# before_action :authenticate_user!, except: [:index, :show]
before_filter :authorize_admin, except: [:index, :show]

def index
	if params[:tag]
		@posts = Post.tagged_with(params[:tag])
	else
		@posts = Post.all.order('created_at DESC')
	end
end

def new
	@post = Post.new
end

def create
	@post = Post.new(post_params)
	if @post.save
			flash[:success] = "Post created"
			redirect_to @post
	else
		flash[:danger] = "Error creating new post!"
		render :new
	end
end

def edit
	@post = Post.friendly.find(params[:id])
end

def update
	@post = Post.friendly.find(params[:id])
	if @post.update(post_params)
		flash[:success] = "Post updated"
		redirect_to @post
	else
		flash[:danger] = "Error updating post!"
		render :edit
	end
end

def show
	@post = Post.friendly.find(params[:id])
end

def destroy
	@post = Post.friendly.find(params[:id])
	@post.destroy
	flash[:success] = "Post deleted"
	redirect_to posts_path
end

def publish
	@post = Post.friendly.find(params[:id])
	@post.published = true
	if @post.save
		redirect_to @post
		flash[:success] = "Post published"
	else
		flash[:alert] = "Error occured"
		redirect_to @post
	end
end

def unpublish
	@post = Post.friendly.find(params[:id])
	@post.published = false
	if @post.save
		redirect_to @post
		flash[:success] = "Post unpublished"
	else
		flash[:alert] = "Error occured"
		redirect_to @post
	end
end

private

def post_params
	params.require(:post).permit(:title, :body, :all_tags, :published)
end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_filter :authorize_admin
	
	def index
		@tags = Tag.all.order('created_at DESC')
	end

	def destroy
		@tag = Tag.find(params[:id])
		@tag.destroy

		if @tag.save
			flash[:success] = "Tag deleted"
			redirect_to tags_path
		else 
			flash[:danger] = "Error occured"
			redirect_to tags_path
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authorize_admin, except: [:new, :create]

	def index
		@user = User.all.order('created_at DESC')
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:success] = "User updated"
			redirect_to @user
		else
			flash[:danger] = "Error updating user!"
			render :edit
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy

		if @user.destroy
			redirect_to root_url, notice: "User deleted"
        end
	end

	private
	
	def user_params
		params.require(:user).permit(:email)
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_attachment_helper.rb
module PostAttachmentHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def tag_links(tags)
  		tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(" ") 
	end

	def tag_cloud(tags, classes)
		max = tags.sort_by(&:count).last
		tags.each do |tag|
			index = tag.count.to_f / max.count * (classes.size-1)
			yield(tag, classes[index.round])
		end
	end
	
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_flash.html.erb
<div class="row">
	<div class="col-xs-8 col-sm-4 col-md-3 col-lg-3 col-centered">
		<% flash.each do |message_type, message| %>
		<%= content_tag(:div, message, class: "flash_messages alert alert-#{message_type}" )  %>
		<% end %>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="form-group">
        <% if @post.errors.any? %>
          <div class="alert alert-danger">
            <ul>
            <% @post.errors.full_messages.each do |msg| %>
              <li>
                <%= msg %>
              </li>
            <% end %>
            </ul>
          </div>
        <% end %>
          <div>
          <p>
            <%= f.text_field :title, class: "form-control", placeholder: "Title of the Post" %>
          </p>
          <p>
              <%= raw f.cktext_area :body, class: "form-control", rows: "15", placeholder: "Body" %>
          </p>
           <p>
              <%= f.text_field :all_tags, class: "form-control", placeholder: "Tags (separated by comma)" %>
          </p>
          <p>
            <%= f.submit "Save", class: "btn btn-default" %>
          </p>
        </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/_post.html.erb
<section>
	<% @posts.each do |post| %>
	<% if post.published.to_s == "true" || current_user.try(:admin?) %>
		<header class="post_header">
			<h2 class="post_title"><%= link_to post.title, post %></h2>
		<% if post.published.to_s == "false" %>
			<h5 class="post_status">(Unpublished)</h5>
		<% end %>
			<h5 class="date"><%= post.created_at.strftime('%B %d, %Y') %>
			<% if post.comments.any? %>
			| Comments: <%= post.comments.count %> 
			<% end %>    	
			</h5>
		</header>
		<article class="post_body">
			<%= raw post.body %>
		</article> 
		<footer class="post_footer">
			<p class="tags"><%= raw tag_links(post.all_tags) %></p>
			<p class="social_share"><%= social_share_button_tag(post.title) %></p>
			<p><hr></p>
		</footer>
	<% end %>	
	<% end %>
</section>

app/views/posts/_post_footer.html.erb
<% if @posts.any? %>

	<footer class="post_footer">
		<p class="social_share"><%= social_share_button_tag(post.title) %></p>
		<p class="tags"><%= raw tag_links(post.all_tags) %></p>
		<p><hr></p>
	</footer>

<% else %>

	<footer class="post_footer">
		<p class="social_share"><%= social_share_button_tag(@post.title) %></p>
		<p class="tags"><%= raw tag_links(@post.all_tags) %></p>
		<p><hr></p>
	</footer>

<% end %>

app/views/posts/edit.html.erb
<article class="post_container">	
	<h2 class="post_title">Editing "<%= @post.title %>"</h2>
	<div class="post_body">
		<%= render "posts/form" %>
	</div>
</article>

app/views/posts/index.html.erb
<% if params[:tag] %>
	<%= render 'post' %>
<% else %>
	<%= render 'post' %>
<% end %>

app/views/posts/new.html.erb
<div class="post_header">
	<h2 class="post_title">Create New Post</h2>
</div>
<div class="post_body">
	<%= render 'posts/form' %>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title + " | " ) %>
<% if @post.published.to_s == "true" || current_user.try(:admin?) %>
	<header class="post_header">
		<h2 class="post_title"><%= @post.title %></h2>
		<% if @post.published.to_s == "false" %>
		<h5 class="post_status">(Unpublished)</h5>
		<% end %>
		<h5 class="date">
			<%= @post.created_at.strftime('%B %d, %Y') %>
			<% if @post.comments.any? %>
			 | Comments: <%= @post.comments.count %>
			<% end %>
		</h5>
		<p>
		<% if current_user.try(:admin?) %>
			<%= link_to ' Edit  ', edit_post_path(@post), class: "btn btn-default btn-xs" %>
			<% if @post.published.to_s == "false" %>
				<%= link_to ' Publish  ', publish_post_path(@post), class: "btn btn-default btn-xs" %>
			<% else %>
				<%= link_to ' Unpublish  ', unpublish_post_path(@post), class: "btn btn-default btn-xs" %>
			<% end %>
			<%= link_to 'Delete', post_path(@post), class: "btn btn-default btn-xs", :method => :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>
		</p>
	</header>
	<article class="post_body">
		<%= raw @post.body %>
	</article>
	<footer class="post_footer">
		<p class="tags"><%= raw tag_links(@post.all_tags) %></p>
		<p class="social_share"><%= social_share_button_tag(@post.title) %></p>
		<p><hr></p>
	</footer>
	<div class="row">
        <div class="col-xs-11 col-sm-11 col-md-11 col-lg-11 col-centered">
        	<% if @post.comments.count > 0 %>
			<h2 class="comment_section">Comments (<%= @post.comments.count %>)</h2>
			<% end %>
			<% @post.comments.each do |comment| %>
			<h5 class="comment_author"><%= comment.commenter %></h5>
			<h5 class="comment_date"><%= comment.created_at.strftime('%H:%M %b %d, %Y') %></h5>
			<p class="comment_body"><%= comment.body %></p>
			<% if current_user.try(:admin?) %>
			<p>
				<%= link_to ' Edit  ', edit_post_comment_path(@post, comment), class: "btn btn-default btn-xs" %>
				<%= link_to 'Delete', [comment.post, comment], class: "btn btn-default btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>
			</p>
			<% end %>
			<p><hr></p>
			<% end %>
			<h2 class="comment_section">Write a comment</h2>
			<%= render 'comments/comment_form' %>
		</div>					
	</div>
	<div class="row">
		<div class="post_bottom_nav hidden-xs col-sm-11 col-md-11 col-lg-11 col-centered">
				<%= link_to "<< Previous Post", @post.prev %>  | 
				<%= link_to "Top of the Page", anchor: "top" %> | 
				<%= link_to "Next Post >>", @post.next %>
		</div>
		<div class="post_bottom_nav visible-xs-11 hidden-sm hidden-md hidden-lg">
			<%= link_to "<< Previous", @post.prev %>  | <%= link_to "Top", anchor: "top" %> | <%= link_to "Next >>", @post.next %>
		</div>
	</div>
<% end %>

app/views/posts/test.html.erb
  <% if @post.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/tags/index.html.erb
<div class="row">
	<div class="col-xs-11 col-sm-11 col-md-11 col-lg-11 col-centered">
		<h2 class="comment_section">All Tags (<%= Tag.count %>)</h2>
		<% @tags.each do |tag| %>
			<p class="tags"><%= link_to tag.name, tag_path(tag.name) %></p>
			<p>Tag ID: <%= tag.id%></p>
			<p>Tag created_at: <%= tag.created_at %></p>
			<p>
			<%= link_to 'Delete', delete_tag_path(tag), class: "btn btn-default btn-xs", :method => :delete, data: { confirm: 'Are you sure?' } %>
			</p>
		<% end %>
	</div>
</div>

<div class="row">
	<div class="col-xs-11 col-sm-11 col-md-11 col-lg-11 col-centered">
		<h2 class="comment_section">All Taggings (<%= Tagging.count %>)</h2>
		<% @taggings = Tagging.all.order('created_at DESC') %>
		<% @taggings.each do |tagging| %>
		<% @post = Post.find(tagging.post_id) %>
		<% @tag = Tag.find(tagging.tag_id) %>
		<ul>
			<li><p>Tagging ID: <%= tagging.id%></p>
				<p>Post: "<%= @post.title %>" (<%= tagging.post_id %>)</p>
				<p class="tags">Tag: <%= @tag.name %> (<%= tagging.tag_id%>)</p>
				<p>
				<%= link_to 'Delete', delete_tagging_path(tagging), class: "btn btn-default btn-xs", :method => :delete, data: { confirm: 'Are you sure?' } %>
				</p>
			</li>
		</ul>
		<% end %>
	</div>
</div>

app/views/users/_manageusers.html.erb
<ol>
	<% @users = User.all.order('created_at ASC') %>
	<% @users.each do |user| %>
	<li>
		Email: <%= user.email %><br>
		User created at: <%= user.created_at %><br>
		<% if user.admin? %>
		<p><strong><%= "ADMIN USER" %></strong></p>
		<% end %>
		<p>
		<%= link_to "Details", admin_show_user_path(user), class: "btn btn-default btn-xs" %>
		<%= link_to "Delete", admin_destroy_user_path(user), method: :delete, class: "btn btn-default btn-xs", data: { confirm: "You sure?" } %>
		</p>
	</li>
	<% end %>
</ol>

app/views/users/index.html.erb
<h2>All Users (<%= User.count %>)</h2>
<ol>
<% @users = User.all.order('created_at ASC') %>
<% @users.each do |user| %>
<li>
Email: <%= user.email %><br>
User created at: <%= user.created_at %><br>
<% if user.admin? %>
<p><strong><%= "ADMIN USER" %></strong></p>
<% end %>
<p>
<%= link_to "Details", admin_show_user_path(user), class: "btn btn-default btn-xs" %>
<%= link_to "Delete", admin_destroy_user_path(user), method: :delete, class: "btn btn-default btn-xs", data: { confirm: "You sure?" } %>
</p>
</li>
<% end %>
</ol>

app/views/users/show.html.erb
<section>
  <h3>Admin Show User</h3>
  <p>Email: <%= @user.email %></p>
  <p>encrypted_password: <%= @user.encrypted_password %></p>
  <p>reset_password_token: <%= @user.reset_password_token %></p>
  <p>reset_password_sent_a: <%= @user.reset_password_sent_at %></p>
  <p>sign_in_count: <%= @user.sign_in_count %></p>
  <p>current_sign_in_at: <%= @user.current_sign_in_at %></p>
  <p>last_sign_in_at: <%= @user.last_sign_in_at %></p>
  <p>current_sign_in_ip: <%= @user.current_sign_in_ip %></p>
  <p>user.created_at: <%= @user.created_at %></p>
  <p>user.updated_at: <%= @user.updated_at %></p>
  <p><%= link_to "Back", :back %></p>
  </section>