config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  
  get '/contact', to: 'messages#new', as: 'contact'
  post '/contact', to: 'messages#create'

  get '/about', to: 'pages#about'

  devise_for :users

  resources :posts do
    resources :comments
  end

  root to: "posts#index"
  match 'posts/:id/publish' => 'posts#publish', :via => :get, :as => :publish_post
  match 'posts/:id/unpublish' => 'posts#unpublish', :via => :get, :as => :unpublish_post

  get 'tags/:tag', to: 'posts#index', as: "tag"
  get 'tags/', to: 'tags#index', as: "tags"
  get 'taggings/', to: 'taggings#index', as: "taggings"
  match 'taggings/:id' => 'taggings#destroy', :via => :delete, :as => :delete_tagging
  match 'tags/:id' => 'tags#destroy', :via => :delete, :as => :delete_tag

  match '/users',   to: 'users#index',   via: 'get'
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'users/:id' => 'users#show', :via => :get, :as => :admin_show_user
  match 'users/:id' => 'users#update', :via => :get, :as => :admin_edit_user

  match '/comments',   to: 'comments#index',   via: 'get', :as => :all_comments
  match '/comments/:id',   to: 'comments#show',   via: 'get', :as => :show_comment

  devise_scope :user do
    get "/admin" => "devise/sessions#new"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	validates :commenter, presence: true, length: {minimum: 1}
	validates :body, presence: true, length: {minimum: 5}
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "your_email@example.org",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/message.rb
class Message

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :content,
    presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :nullify
  has_many :tags, dependent: :nullify, through: :taggings

	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true

	extend FriendlyId
	friendly_id :title, use: :slugged

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
  end

  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end

 def next
 	 Post.where("id > ?", id).limit(1).first
	end

	def prev
  	Post.where("id < ?", id).limit(1).first
	end

	has_many :post_attachments
 	accepts_nested_attributes_for :post_attachments
end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
	mount_uploader :post_image, PostImageUploader
   	belongs_to :post
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings, dependent: :destroy
	has_many :posts, dependent: :nullify, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end

	def manage
	end
	
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_filter :authorize_admin
	
	def index
		@tags = Tag.all.order('created_at DESC')
	end

	def destroy
		@tag = Tag.find(params[:id])
		@tag.destroy

		if @tag.save
			flash[:success] = "Tag deleted"
			redirect_to tags_path
		else 
			flash[:danger] = "Error occured"
			redirect_to tags_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def tag_links(tags)
  		tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(" ") 
	end

	def tag_cloud(tags, classes)
		max = tags.sort_by(&:count).last
		tags.each do |tag|
			index = tag.count.to_f / max.count * (classes.size-1)
			yield(tag, classes[index.round])
		end
	end
	
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= yield(:title) unless :title == nil %> Giedrius Rimkus - Personal Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag Ckeditor.cdn_url %>
  <%= csrf_meta_tags %>
</head>
<body>
<script>
	$('a[href="' + this.location.pathname + '"]').parents('li,ul').addClass('active');
</script>
<div class="row">
	<nav class="main_nav navbar navbar-inverse col-xs-12 col-sm-12 col-md-10 col-lg-10 col-centered">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
		        	<span class="icon-bar"></span>
		        	<span class="icon-bar"></span>
		        	<span class="icon-bar"></span>                        
      			</button>
				<%= link_to root_path do %>
      			<div class="navbar-brand"></div>
      			<% end %>
			</div>
				<div class="collapse navbar-collapse" id="myNavbar">
					<ul class="nav navbar-nav">
						<li>
							<%= link_to root_path do %>
		      				<span class="glyphicon glyphicon-home"></span>&nbsp; &nbsp;HOME
		      				<% end %>
		      			</li>
			            <li>
			            	<%= link_to about_path do %>
			            	<span class="glyphicon glyphicon-user"></span>&nbsp; &nbsp;ABOUT
							<% end %>
			            </li>
						<li>
							<%= link_to contact_path do %>
							<span class="glyphicon glyphicon-envelope"></span>&nbsp; &nbsp;CONTACT
							<% end %>
						</li>
						<% if user_signed_in?  %>
						<li>
						<%= link_to edit_user_registration_path do %>
						<span class=""></span>Profile
							<% end %>
						</li>
						<% end %>
					<% if current_user.try(:admin?)%>
						<li><%= link_to "Create", new_post_path, class: "admin_button" %></li>
						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#">Manage<span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li>
								<%= link_to users_path do %>
									Users (<%= User.count %>)
								<% end %>
								</li>
								<li>
								<%= link_to all_comments_path do %>
									Comments (<%= Comment.count %>)
								<% end %>
								</li>
								<li>
								<%= link_to tags_path do %>
									Tags (<%= Tag.count %>)
								<% end %>
								</li>
							</ul>
						</li>
					<% end %>
					</ul>
					<% if user_signed_in?  %>
					<ul class="nav navbar-nav navbar-right">
					<li>
						<%= link_to destroy_user_session_path, :method => :delete do %>
							<span class="glyphicon glyphicon-log-out"></span>&nbsp;Logout
						<% end %>
					</li>
	      			</ul>
	      			<% end %>
	    </div>
	</nav>
</div>
	<div class="container-fluid">
		<div class="row">
  			<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 col-centered">
				<%= render "posts/flash" %>
				<%= yield %>
			</div>
		</div>
	</div>
<footer id="main"></footer>
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About | ") %>
<article class="about_page">
	<header class="post_header">
		<h2 class="post_title">About Me</h2>
	</header>
	<p>Hello!</p>
	<p>Labadiena.</p>
</article>

app/views/pages/manage.html.erb
<% provide(:title, "Manage Blog | ") %>
<h3>Edit Profile</h3>
<p><%= link_to "Update Profile", edit_user_registration_path, class: "user_button"%></p>
<h3>All Users (<%= User.count %>)</h3>
<br>
<%= render "users/manageusers" %>

<h3>All Comments (<%= Comment.count %>)</h3>
<br>
<%= render "comments/managecomments" %>